<a href="https://colab.research.google.com/github/preetamjumech/imputation_handling_imbalanced_bow_quora/blob/main/Handling_Imbalanced_Dataset_19_01_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

from sklearn.metrics import confusion_matrix

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report

In [ ]:
data= pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [ ]:
data.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [ ]:
data.shape

(7043, 21)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [ ]:
data.columns.tolist()

['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn']

In [ ]:
data.nunique()

customerID          7043
gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
tenure                73
PhoneService           2
MultipleLines          3
InternetService        3
OnlineSecurity         3
OnlineBackup           3
DeviceProtection       3
TechSupport            3
StreamingTV            3
StreamingMovies        3
Contract               3
PaperlessBilling       2
PaymentMethod          4
MonthlyCharges      1585
TotalCharges        6531
Churn                  2
dtype: int64

In [ ]:
data["TotalCharges"]

0         29.85
1        1889.5
2        108.15
3       1840.75
4        151.65
         ...   
7038     1990.5
7039     7362.9
7040     346.45
7041      306.6
7042     6844.5
Name: TotalCharges, Length: 7043, dtype: object

In [ ]:
data["TotalCharges"].iloc[488]

' '

In [ ]:
data.iloc[488]

customerID                         4472-LVYGI
gender                                 Female
SeniorCitizen                               0
Partner                                   Yes
Dependents                                Yes
tenure                                      0
PhoneService                               No
MultipleLines                No phone service
InternetService                           DSL
OnlineSecurity                            Yes
OnlineBackup                               No
DeviceProtection                          Yes
TechSupport                               Yes
StreamingTV                               Yes
StreamingMovies                            No
Contract                             Two year
PaperlessBilling                          Yes
PaymentMethod       Bank transfer (automatic)
MonthlyCharges                          52.55
TotalCharges                                 
Churn                                      No
Name: 488, dtype: object

In [ ]:
data["TotalCharges"] = data["TotalCharges"].replace(r"\s+",np.nan, regex= True)
data["TotalCharges"] = pd.to_numeric(data["TotalCharges"])

In [ ]:
fill = data["MonthlyCharges"]*data["tenure"]

In [ ]:
fill

0         29.85
1       1936.30
2        107.70
3       1903.50
4        141.40
         ...   
7038    2035.20
7039    7430.40
7040     325.60
7041     297.60
7042    6972.90
Length: 7043, dtype: float64

In [ ]:
data["TotalCharges"].fillna(fill,inplace = True, axis = 0)

In [ ]:
data.iloc[488]

customerID                         4472-LVYGI
gender                                 Female
SeniorCitizen                               0
Partner                                   Yes
Dependents                                Yes
tenure                                      0
PhoneService                               No
MultipleLines                No phone service
InternetService                           DSL
OnlineSecurity                            Yes
OnlineBackup                               No
DeviceProtection                          Yes
TechSupport                               Yes
StreamingTV                               Yes
StreamingMovies                            No
Contract                             Two year
PaperlessBilling                          Yes
PaymentMethod       Bank transfer (automatic)
MonthlyCharges                          52.55
TotalCharges                              0.0
Churn                                      No
Name: 488, dtype: object

In [ ]:
data["OnlineSecurity"].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [ ]:
data["Churn"].unique()

array(['No', 'Yes'], dtype=object)

In [ ]:
cols = ['Churn']
for col in cols:
  data[col] = data[col].replace("Yes",1).replace("No",0)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [ ]:
data.iloc[488]

customerID                         4472-LVYGI
gender                                 Female
SeniorCitizen                               0
Partner                                   Yes
Dependents                                Yes
tenure                                      0
PhoneService                               No
MultipleLines                No phone service
InternetService                           DSL
OnlineSecurity                            Yes
OnlineBackup                               No
DeviceProtection                          Yes
TechSupport                               Yes
StreamingTV                               Yes
StreamingMovies                            No
Contract                             Two year
PaperlessBilling                          Yes
PaymentMethod       Bank transfer (automatic)
MonthlyCharges                          52.55
TotalCharges                              0.0
Churn                                       0
Name: 488, dtype: object

In [ ]:
data["SeniorCitizen"].unique()

array([0, 1])

In [ ]:
data["gender"].unique()

array(['Female', 'Male'], dtype=object)

In [ ]:
data["MultipleLines"].unique()

array(['No phone service', 'No', 'Yes'], dtype=object)

In [ ]:
data["InternetService"].unique()

array(['DSL', 'Fiber optic', 'No'], dtype=object)

In [ ]:
data["Contract"].unique()

array(['Month-to-month', 'One year', 'Two year'], dtype=object)

In [ ]:
data["PaymentMethod"].unique()

array(['Electronic check', 'Mailed check', 'Bank transfer (automatic)',
       'Credit card (automatic)'], dtype=object)

In [ ]:
data = pd.get_dummies(data= data, columns=['gender','MultipleLines','PaymentMethod','InternetService','Contract','Partner','Dependents','PhoneService','OnlineSecurity','OnlineBackup','DeviceProtection','TechSupport','StreamingTV','StreamingMovies','PaperlessBilling'],drop_first = True)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 32 columns):
 #   Column                                 Non-Null Count  Dtype  
---  ------                                 --------------  -----  
 0   customerID                             7043 non-null   object 
 1   SeniorCitizen                          7043 non-null   int64  
 2   tenure                                 7043 non-null   int64  
 3   MonthlyCharges                         7043 non-null   float64
 4   TotalCharges                           7043 non-null   float64
 5   Churn                                  7043 non-null   int64  
 6   gender_Male                            7043 non-null   uint8  
 7   MultipleLines_No phone service         7043 non-null   uint8  
 8   MultipleLines_Yes                      7043 non-null   uint8  
 9   PaymentMethod_Credit card (automatic)  7043 non-null   uint8  
 10  PaymentMethod_Electronic check         7043 non-null   uint8  
 11  Paym

In [ ]:
data.drop(["customerID"],axis = 1,inplace = True)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
data["Churn"].value_counts()

0    5174
1    1869
Name: Churn, dtype: int64

In [ ]:
df_train = data[:5001]
df_test = data[5001:]

X_test = df_test.drop(["Churn"],axis = 1)
y_test = df_test["Churn"]

# Up and down sampling using sklearn

In [ ]:
df_majority = df_train[df_train["Churn"]==0]
df_minority = df_train[df_train["Churn"]==1]
print(df_majority.shape, df_minority.shape)

(3688, 31) (1313, 31)


In [ ]:
from sklearn.utils import resample

### Upsampling

In [ ]:
df_minority_upsampled = resample(df_minority, n_samples = df_majority.shape[0], random_state=2,replace = True)

In [ ]:
df_upsampled = pd.concat([df_majority,df_minority_upsampled],axis = 0)
print(df_upsampled.shape)

(7376, 31)


In [ ]:
df_upsampled["Churn"].value_counts()

0    3688
1    3688
Name: Churn, dtype: int64

In [ ]:
X_up = df_upsampled.drop(["Churn"],axis = 1)
y_up = df_upsampled["Churn"]

In [ ]:
from sklearn.linear_model import LogisticRegression
lg = LogisticRegression(penalty="l2",solver = "liblinear").fit(X_up,y_up)
y_pred = lg.predict(X_test)

print("accuracy_score : ",accuracy_score(y_test,y_pred))
print("precision_score : ",precision_score(y_test,y_pred))
print("recall_score : ",recall_score(y_test,y_pred))
print("f1_score : ",f1_score(y_test,y_pred))
target_names = ['class 0', 'class 1']
print(classification_report(y_test, y_pred, target_names=target_names))
print(confusion_matrix(y_test,y_pred))

accuracy_score :  0.7463271302644466
precision_score :  0.5233415233415234
recall_score :  0.7661870503597122
f1_score :  0.6218978102189782
              precision    recall  f1-score   support

     class 0       0.89      0.74      0.81      1486
     class 1       0.52      0.77      0.62       556

    accuracy                           0.75      2042
   macro avg       0.71      0.75      0.72      2042
weighted avg       0.79      0.75      0.76      2042

[[1098  388]
 [ 130  426]]


### Down sampling

In [ ]:
df_majority_downsampled = resample(df_majority,n_samples = df_minority.shape[0],random_state=2, replace=True)

In [ ]:
df_downsampled = pd.concat([df_minority,df_majority_downsampled],axis = 0)
print(df_downsampled.shape)

(2626, 31)


In [ ]:
df_downsampled["Churn"].value_counts()

1    1313
0    1313
Name: Churn, dtype: int64

In [ ]:
X_down = df_downsampled.drop(["Churn"],axis = 1)
y_down = df_downsampled["Churn"]

In [ ]:
from sklearn.linear_model import LogisticRegression
lg = LogisticRegression(penalty="l2",solver = "liblinear").fit(X_down,y_down)
y_pred = lg.predict(X_test)

print("accuracy_score : ",accuracy_score(y_test,y_pred))
print("precision_score : ",precision_score(y_test,y_pred))
print("recall_score : ",recall_score(y_test,y_pred))
print("f1_score : ",f1_score(y_test,y_pred))
target_names = ['class 0', 'class 1']
print(classification_report(y_test, y_pred, target_names=target_names))
print(confusion_matrix(y_test,y_pred))

accuracy_score :  0.7438785504407444
precision_score :  0.5204460966542751
recall_score :  0.7553956834532374
f1_score :  0.6162876008804108
              precision    recall  f1-score   support

     class 0       0.89      0.74      0.81      1486
     class 1       0.52      0.76      0.62       556

    accuracy                           0.74      2042
   macro avg       0.71      0.75      0.71      2042
weighted avg       0.79      0.74      0.76      2042

[[1099  387]
 [ 136  420]]


### Smote (Synthetic Minority Oversampling Technique)

In [ ]:
df_train["Churn"].value_counts()

0    3688
1    1313
Name: Churn, dtype: int64

In [ ]:
X_train = df_train.drop(["Churn"],axis = 1)
y_train = df_train["Churn"]

In [ ]:
print(X_train.shape,y_train.shape)

(5001, 30) (5001,)


In [ ]:
y_train.ravel()

array([0, 0, 1, ..., 0, 0, 0])

In [ ]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=2)
X_train_res , y_train_res = sm.fit_resample(X_train,y_train.ravel())

In [ ]:
print(X_train_res.shape,y_train_res.shape)

(7376, 30) (7376,)


In [ ]:
print(y_train_res[y_train_res==0].shape)
print(y_train_res[y_train_res==1].shape)

(3688,)
(3688,)


In [ ]:
from sklearn.linear_model import LogisticRegression
lg = LogisticRegression(penalty="l2",solver = "liblinear").fit(X_train_res,y_train_res)
y_pred = lg.predict(X_test)

print("accuracy_score : ",accuracy_score(y_test,y_pred))
print("precision_score : ",precision_score(y_test,y_pred))
print("recall_score : ",recall_score(y_test,y_pred))
print("f1_score : ",f1_score(y_test,y_pred))
target_names = ['class 0', 'class 1']
print(classification_report(y_test, y_pred, target_names=target_names))
print(confusion_matrix(y_test,y_pred))

accuracy_score :  0.77179236043095
precision_score :  0.5707547169811321
recall_score :  0.6528776978417267
f1_score :  0.6090604026845637
              precision    recall  f1-score   support

     class 0       0.86      0.82      0.84      1486
     class 1       0.57      0.65      0.61       556

    accuracy                           0.77      2042
   macro avg       0.72      0.73      0.72      2042
weighted avg       0.78      0.77      0.78      2042

[[1213  273]
 [ 193  363]]


### Adasyn

In [ ]:
df_train["Churn"].value_counts()

0    3688
1    1313
Name: Churn, dtype: int64

In [ ]:
X_train = df_train.drop(["Churn"],axis = 1)
y_train = df_train["Churn"]

In [ ]:
from imblearn.over_sampling import ADASYN
ada = ADASYN(random_state=2)
X_train_res , y_train_res = ada.fit_resample(X_train,y_train.ravel())

In [ ]:
print(X_train_res.shape,y_train_res.shape)

(7362, 30) (7362,)


In [ ]:
from sklearn.linear_model import LogisticRegression
lg = LogisticRegression(penalty="l2",solver = "liblinear").fit(X_train_res,y_train_res)
y_pred = lg.predict(X_test)

print("accuracy_score : ",accuracy_score(y_test,y_pred))
print("precision_score : ",precision_score(y_test,y_pred))
print("recall_score : ",recall_score(y_test,y_pred))
print("f1_score : ",f1_score(y_test,y_pred))
target_names = ['class 0', 'class 1']
print(classification_report(y_test, y_pred, target_names=target_names))
print(confusion_matrix(y_test,y_pred))

accuracy_score :  0.7703232125367288
precision_score :  0.568503937007874
recall_score :  0.6492805755395683
f1_score :  0.6062132661628884
              precision    recall  f1-score   support

     class 0       0.86      0.82      0.84      1486
     class 1       0.57      0.65      0.61       556

    accuracy                           0.77      2042
   macro avg       0.71      0.73      0.72      2042
weighted avg       0.78      0.77      0.77      2042

[[1212  274]
 [ 195  361]]


### SMOTE + ENN

In [ ]:
df_train["Churn"].value_counts()

0    3688
1    1313
Name: Churn, dtype: int64

In [ ]:
X_train = df_train.drop(["Churn"],axis = 1)
y_train = df_train["Churn"]

In [ ]:
from imblearn.combine import SMOTEENN
smenn = SMOTEENN(random_state=2)
X_train_res , y_train_res = smenn.fit_resample(X_train,y_train.ravel())

In [ ]:
print(X_train_res.shape,y_train_res.shape)

(4204, 30) (4204,)


In [ ]:
print(y_train_res[y_train_res==0].shape)
print(y_train_res[y_train_res==1].shape)

(1943,)
(2261,)


In [ ]:
from sklearn.linear_model import LogisticRegression
lg = LogisticRegression(penalty="l2",solver = "liblinear").fit(X_train_res,y_train_res)
y_pred = lg.predict(X_test)

print("accuracy_score : ",accuracy_score(y_test,y_pred))
print("precision_score : ",precision_score(y_test,y_pred))
print("recall_score : ",recall_score(y_test,y_pred))
print("f1_score : ",f1_score(y_test,y_pred))
target_names = ['class 0', 'class 1']
print(classification_report(y_test, y_pred, target_names=target_names))
print(confusion_matrix(y_test,y_pred))

accuracy_score :  0.7664054848188051
precision_score :  0.5546334716459198
recall_score :  0.7212230215827338
f1_score :  0.6270523846755277
              precision    recall  f1-score   support

     class 0       0.88      0.78      0.83      1486
     class 1       0.55      0.72      0.63       556

    accuracy                           0.77      2042
   macro avg       0.72      0.75      0.73      2042
weighted avg       0.79      0.77      0.77      2042

[[1164  322]
 [ 155  401]]
